highlighter: pygments
permalink: pretty
markdown: kramdown

title: opencats
description: "vim's rebirth for the 21st century"

news:
    name: opencats Newsletter
    authors: opencats Community
    url: http://opencats.org/news
    feed: /news.xml

url: "http://opencats.org"

gems:
    - jekyll-redirect-from
    - jekyll-mentions

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
